global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: nodeexporter
    scrape_interval: 5s
    static_configs:
      - targets: ['scripts-node-exporter-1:9100']

  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: ['app-nextjs-1:3000']
      
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['scripts-cadvisor-1:8080']